# Use an official Node.js runtime as the base image
FROM node:16.19.1

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install npm dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 (the default port used by create-react-app)
EXPOSE 3000

# Define the command to start the application
CMD ["npm", "start"]
